@host=http://localhost:5282

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Musa",
    "lastName": "Zulu",
    "email": "zuluchs@gmail.com",
    "password": "Musa1232!"
}

